
angular.module('MatWeb', [
  'ngRoute',
  'nucleo',
  'Cadastrar',
  'Cadastrarusuario',
  'DadosUsuario',
  'Cadastrarcurso',
  'Cadastrarpredio',
  'Home',
  'Usuario',
  'Admin',
  'Oferta',
  'Campus',
  'Curso',
  'Registrodesala',
  'Cadastrarmateria',
  'Predio',
  'Departamento',
  'Disciplina',
  'Registrodesala',
  'Sala',
  'Curso',
  'Grade',
  'Matricular',
  'ui.bootstrap',
  'angular.filter'
]); 
